parent=keycloak.v2
styles=css/styles.css css/sq-account-hcis-f7a4c91d2e36.css css/hcis-logo-assets-294b82789923.css
locales=id
darkMode=false
favicons.svg=img/favicon.svg
favicons.svg.type=image/svg+xml
contentHashPattern=^css/(sq-account-hcis|hcis-logo-assets)-[0-9a-f]{12}[.]css$
