parent=keycloak.v2
styles=css/styles.css css/akun-sq-login-a7cdc6626ac7.css
locales=id
darkMode=false
favicons.svg=img/favicon.svg
favicons.svg.type=image/svg+xml
contentHashPattern=^css/akun-sq-login-[0-9a-f]{12}[.]css$
