parent=keycloak.v2
styles=css/styles.css css/sq-identity-066c6982e041.css css/sq-account-41ad9ff20ec3.css
locales=id
darkMode=false
favicons.svg=img/favicon.svg
favicons.svg.type=image/svg+xml
contentHashPattern=^css/sq-account-[0-9a-f]{12}[.]css$
