parent=keycloak.v3
darkMode=false
locales=id
styles=css/akun-sq-account-4dfec5ffce69.css
logo=img/ysq-mark.png
logoUrl=/
title=Akun SQ
description=Yayasan Sabilul Qur'an
favicons.svg=img/favicon.svg
favicons.svg.type=image/svg+xml
contentHashPattern=^css/akun-sq-account-[0-9a-f]{12}[.]css$
