import { describe, expect, it } from "vitest";

import { buildApp } from "../src/app.js";
import { HubAuthError, type HubAuthRuntime } from "../src/modules/hub-auth/service.js";
import type { OrganizationalUnitService } from "../src/modules/organizational-units/service.js";
import { PlatformAdminAuthorizationError } from "../src/modules/platform-admin/service.js";

const origin = "https://hub-staging.example.test";
const session = { sessionId: "org-admin", issuer: "https://login.example.test/realms/staff", subject: "admin-subject", displayName: "Admin", createdAt: new Date("2026-09-04T01:00:00Z"), expiresAt: new Date("2026-09-04T12:00:00Z") };
function hub(overrides: Partial<HubAuthRuntime> = {}): HubAuthRuntime { return { beginLogin: async () => ({ authorizationUrl: new URL("https://login.example.test"), setCookie: "x" }), completeLogin: async () => ({ setCookies: [] }), getWorkspace: async () => ({ user: { displayName: "Admin", initials: "A" }, applications: [], capabilities: { platformAdministration: true } }), getSession: async () => session, logout: async () => ({ clearCookie: "x", logoutUrl: null }), clearTransactionCookie: () => "x", ...overrides }; }
function service(calls: string[] = []): OrganizationalUnitService { return { list: async () => { calls.push("list"); return []; }, hierarchy: async () => [], create: async () => { calls.push("create"); return { id: "33333333-3333-4333-8333-333333333333" }; }, update: async () => { calls.push("update"); return {}; }, setActive: async () => { calls.push("status"); return { outcome: "succeeded", unit: {} }; }, inspectImport: () => ({ valid: true }), previewImport: async () => ({ valid: true, issues: [], creates: [], updates: [], unchanged: [], fingerprint: "a".repeat(64), ownershipState: "PRE_CUTOVER", sourceSystem: "hcis", implicitDeletions: 0 }), applyImport: async () => { calls.push("apply"); return { outcome: "succeeded", deleted: 0 }; } } as unknown as OrganizationalUnitService; }
function app(input: { authorize?: () => Promise<void>; hubAuth?: HubAuthRuntime; calls?: string[] }) { return buildApp({ accessService: { checkAccess: async () => ({ allowed: true, applicationKey: "hcis", decision: "active_grant" }) }, verifyMachineToken: async () => ({ clientId: "test" }), hubAuth: input.hubAuth ?? hub(), hubRedirectUri: `${origin}/auth/callback`, adminAllowedOrigin: origin, platformAdmin: { authorize: input.authorize ?? (async () => undefined) }, organizationalUnits: service(input.calls) }); }
const headers = { cookie: "sq_hub_session=opaque", origin, "content-type": "application/json" };

describe("Organizational Unit admin routes", () => {
  it("requires authentication", async () => { const instance = app({ hubAuth: hub({ getSession: async () => { throw new HubAuthError(401, "UNAUTHENTICATED", "missing"); } }) }); const response = await instance.inject({ method: "GET", url: "/admin/organizational-units" }); await instance.close(); expect(response.statusCode).toBe(401); });
  it("denies ordinary and stale privileged sessions", async () => { for (const code of ["ADMIN_FORBIDDEN", "ADMIN_REAUTH_REQUIRED"] as const) { const calls: string[] = []; const instance = app({ calls, authorize: async () => { throw new PlatformAdminAuthorizationError(code); } }); const response = await instance.inject({ method: "POST", url: "/admin/organizational-units", headers, payload: { unitKey: "new-unit", name: "New Unit", parentId: null, active: true, reason: "test" } }); await instance.close(); expect(response.statusCode).toBe(403); expect(calls).toEqual([]); } });
  it("rejects mutation from untrusted Origin", async () => { const calls: string[] = []; const instance = app({ calls }); const response = await instance.inject({ method: "POST", url: "/admin/organizational-units", headers: { ...headers, origin: "https://evil.example.test" }, payload: { unitKey: "new-unit", name: "New Unit", parentId: null, active: true, reason: "test" } }); await instance.close(); expect(response.statusCode).toBe(403); expect(calls).toEqual([]); });
  it("keeps preview read-only and apply explicit", async () => { const calls: string[] = []; const instance = app({ calls }); const preview = await instance.inject({ method: "POST", url: "/admin/organizational-units/import/preview", headers: { cookie: headers.cookie, "content-type": "application/json" }, payload: { sourceSystem: "hcis", rows: [], mappings: [] } }); expect(preview.statusCode).toBe(200); expect(calls).toEqual([]); const invalidApply = await instance.inject({ method: "POST", url: "/admin/organizational-units/import/apply", headers, payload: { sourceSystem: "hcis", rows: [], mappings: [], reason: "test", confirm: false } }); await instance.close(); expect(invalidApply.statusCode).toBe(400); expect(calls).toEqual([]); });
});
